name = "Origins Revival"
author = "OhItsElectric"
version = "0.1.8"
description = "Origins.. has been revived once again.."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a757e1741b6cbd2be5d85cfcbbcdf0520a4fc0b2ec9d50b57d3012fa98c51b6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
