name = "Origins Revival"
author = "OhItsElectric"
version = "0.2.0"
description = "Origins.. has been revived once again.."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c40774f4d236d84b34960b910210da54e2d90f6e2c1a7460debb7441a4d9cbb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
