name = "Origins Revival"
author = "OhItsElectric"
version = "0.1.6"
description = "Origins.. has been revived once again.."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d8fce32615ee652eb6fb9ac53f9f09b5f57b7c549a5048ca21a8a924c3ae47d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
